name: clean_arch_gen
description: "A Dart package for clean architecture generation and file execution."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.0

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.21.0
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  mockito: ^5.5.0

# コマンドライン実行可能ファイルの設定
executables:
  clean_arch_gen:
